import React from "react";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Application Layout",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className={cn("bg-background font-sans antialiased", inter.className)}>
        <div className="flex flex-col min-h-screen">
          <header className="bg-muted h-16 flex items-center justify-center">
            {/* Header Content (e.g., Logo, Navigation) */}
            <p className="text-primary font-bold">Application Header</p>
          </header>
          <main className="flex-1 p-4">{children}</main>
          <footer className="bg-muted h-12 flex items-center justify-center">
            {/* Footer Content (e.g., Copyright) */}
            <p className="text-primary text-sm">© {new Date().getFullYear()} Application Footer</p>
          </footer>
        </div>
      </body>
    </html>
  );
}